apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
  namespace: flowin
  labels:
    app: reservation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      containers:
        - name: reservation-service
          image: kkoj/reservation-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8400
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms256m -Xmx512m -Dserver.port=8400"

            # DB 설정 (reservation_db)
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/reservation_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password

            # Redis & Kafka
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: redis-password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"

          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"

          livenessProbe:
            tcpSocket:
              port: 8400
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 8400
            initialDelaySeconds: 15
            periodSeconds: 10