apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: flowin
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: kkoj/payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8300
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms256m -Xmx512m -Dserver.port=8300"

            # DB 설정 (payment_db)
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service.flowin:3306/payment_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
#              valueFrom:
#                secretKeyRef:
#                  name: db-secret
#                  key: password

            # Redis & Kafka
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-service.flowin"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: redis-password
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service.flowin:9092"

          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"

          livenessProbe:
            tcpSocket:
              port: 8300
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 8300
            initialDelaySeconds: 15
            periodSeconds: 10