apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-manager
  namespace: infra-gateway
  labels:
    app: nginx-proxy-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx-proxy-manager
  template:
    metadata:
      labels:
        app: nginx-proxy-manager
    spec:
      containers:
        - name: npm
          image: jc21/nginx-proxy-manager:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
            - containerPort: 81
              name: admin-ui
            - containerPort: 443
              name: https

          volumeMounts:
            - name: npm-data
              mountPath: /data
            - name: npm-letsencrypt
              mountPath: /etc/letsencrypt

      volumes:
        - name: npm-data
          persistentVolumeClaim:
            claimName: npm-pvc
        - name: npm-letsencrypt
          persistentVolumeClaim:
            claimName: npm-pvc # 하나의 PVC를 두 경로에 나눠 써도 무방합니다.