name: Gateway Service CD (Test)

on:
  push:
    branches:
      - FI-222_feat_cd-sc-2
    paths:
      - 'FLOWIN/gateway-service/**'

jobs:
  tagging:
    uses: ./.github/workflows/cd-tagging-script.yml
    secrets: inherit
    permissions:
      contents: write
      attestations: write
      packages: write
    with:
      service-name: gateway-service

  releasing:
    needs: tagging
    uses: ./.github/workflows/cd-release-script.yml
    secrets: inherit
    permissions:
      contents: write
      attestations: write
      packages: write
    with:
      service-name: gateway-service
      tag_name: ${{ needs.tagging.outputs.tag_name }}

  deploy:
    needs: tagging, releasing
    uses: ./.github/workflows/cd-deploy-script.yml
    secrets: inherit
    permissions:
      contents: write
      attestations: write
      packages: write
    with:
      service-name: gateway-service
      tag_name: ${{ needs.tagging.outputs.tag_name }}