name: Performance Service CD (Test)

on:
  push:
    branches:
      - main
    paths:
      - 'FLOWIN/performance-service/**'

jobs:
  tagging:
    uses: ./.github/workflows/cd-tagging-script.yml
    secrets: inherit
    permissions:
      contents: write
      attestations: write
      packages: write
    with:
      service-name: performance-service

  releasing:
    needs: tagging
    uses: ./.github/workflows/cd-release-script.yml
    secrets: inherit
    permissions:
      contents: write
      attestations: write
      packages: write
    with:
      service-name: performance-service
      tag_name: ${{ needs.tagging.outputs.tag_name }}

  deploy:
    needs: [tagging, releasing]
    uses: ./.github/workflows/cd-deploy-script.yml
    secrets: inherit
    permissions:
      contents: write
      attestations: write
      packages: write
    with:
      service-name: performance-service
      tag_name: ${{ needs.tagging.outputs.tag_name }}