name: reservation-service ci/cd #필요 시 이거 이름 바꿔야 함

on:
  workflow_call:

jobs:
  releasing:
    uses: ./.github/workflows/cd-release-script.yml
    secrets: inherit
    permissions:
      contents: write
      attestations: write
      packages: write
    with:
      service-name: reservation-service #필요 시 이것도 바꿔야 함